[package]
name = "frostbite-parser"

version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
lalrpop = "0.20.0"

[dependencies]
frostbite-report-interface = { path = "../frostbite-report-interface" }
derive_more = { workspace = true }
const_format = "0.2.32"
logos = { version = "0.13.0", default-features = false, features = [
    "export_derive",
] }
num-traits = { version = "0.2.17", default-features = false }
