[workspace]
package.version = "0.1.0"
package.edition = "2021"

resolver = "2"

members = ["frostbite-*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.clippy]
rust_2018_idioms = "forbid"
