[workspace]
package.version = "0.1.0"
package.edition = "2021"

resolver = "2"

members = ["frostbite-*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Utility crates commonly used
[workspace.dependencies]
derive_more = "0.99.17"

[lints.clippy]
rust_2018_idioms = "forbid"
