[package]
name = "frostbite-repl"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reedline = "0"

frostbite-compiler = { path = "../compiler" }
frostbite-runtime = { path = "../runtime" }
frostbite-reports = { path = "../reports", features = ["std"] }

[lints]
workspace = true
