[package]
name = "frostbite-bytecode"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ciborium = { version = "0.2.1", default-features = false }

derive_more = { workspace = true }
serde = { version = "1.0.193", default-features = false, features = ["derive"] }
slab = { version = "0.4.9", default-features = false, features = ["serde"] }

[lints]
workspace = true
