[package]
name = "frostbite-bytecode"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = { version = "1.3.0", default-features = false, features = ["derive"] }
derive_more = { workspace = true }

[lints]
workspace = true
